package com.vidanaestrada.domain.entity.vehicle;

public enum VEHICLE_CATEGORY {
    HIGH_PERFORMANCE, //TRANSPORTE RODOVIÁRIO DE CARGA LOTAÇÃO DE ALTO DESEMPENHO
    LOAD_CAPACITY, //Carga lotação
    MOTOR_VEHICLE //OPERAÇÕES EM QUE HAJA A CONTRATAÇÃO APENAS DO VEÍCULO AUTOMOTOR DE CARGAS
}
